### ISSUE TITLE
Unable to login to Genshin Impact

### ISSUE THREAD

**Issue by MaddPenguin** [VHSgunzo/lutris-wine#1]
Getting connection error when trying to login. Tried with twitter login and using email and pass.

Game version: 2.6.0

Logs from running the game from console:
https://pastebin.com/PdACPKb3

**Comment by VHSgunzo** [comment]
The patch seems to be applied... hmm, then do a debug and send it to me too

either that
lutris-wine -debug GenshinImpact.exe

**Comment by MaddPenguin** [comment]
[GenshinImpact_2022-03-31_220312.log](https://github.com/VHSgunzo/lutris-wine/files/8390141/GenshinImpact_2022-03-31_220312.log)

**Comment by VHSgunzo** [comment]
[ Disk info ] : fuseblk

Apparently, the game is on an NTFS disk. Maybe that's the problem.
Many games don't work fine with NTFS drives via Wine, especially online games.  
I advise you to install the game again on ext or btrfs disk using Lutris Wine.
(Not just by copying the game from NTFS)

**Comment by MaddPenguin** [comment]
That's a lot to redownload. I'll queue it up before sleep

**Comment by MaddPenguin** [comment]
I installed the game with lutris-wine this time. Unfortunately it is still the same.

Logs:
[GenshinImpact_2022-04-01_064509.log](https://github.com/VHSgunzo/lutris-wine/files/8393488/GenshinImpact_2022-04-01_064509.log)

**Comment by VHSgunzo** [comment]
Hi, I think there is something wrong with the network settings on your system. 
I check the login in this game every time, it is successful. In any case, 
if the patch had not been applied, the game would simply not have started. 
I have now listened to my traffic at the time of a successful login to the account and caught which servers the game is knocking on. 
Try to open Lutris Wine CMD (<lutris-wine -cmd> or from menu) and ping these servers: 
```
sdk-os-static.hoyoverse.com  ->  443,tcp
autopatchhk.yuanshen.com  ->  443,tcp
log-upload-os.hoyoverse.com  ->  80,tcp
osusadispatch.yuanshen.com  ->  443,tcp
abtest-api-data-sg.hoyoverse.com  ->  443,tcp
static.geetest.com  ->  443,tcp
api-na.geetest.com  ->  443,tcp
api-account-os.hoyoverse.com  ->  443,tcp
hk4e-sdk-os-static.hoyoverse.com  ->  443,tcp
hk4e-sdk-os.hoyoverse.com  ->  443,tcp
osasiadispatch.yuanshen.com  ->  443,tcp
oseurodispatch.yuanshen.com  ->  443,tcp
dispatchosglobal.yuanshen.com  ->  443,tcp
```

Do you have other online games or maybe a launcher like steam or epic game or others installed through Lutris Wine? 
Do they have access to the network?
Maybe a firewall is blocking access to the network for Lutris Wine?

**Comment by VHSgunzo** [comment]
Well, the firewall blocked access to the network for Wine. 
Can you create a new test account? 
Just make sure that all Wine processes are killed before starting a new session. 
Is your current account not blocked?

**Comment by MaddPenguin** [comment]
> Can you create a new test account?

I can create a new account and request a password reset, and by some freak accident, I was able to log in to the new account and play the intro.
But once I sign out to try my other account, I'm back to not being able to sign in for both accounts.




> Is your current account not blocked?

I was just playing on my windows machine

**Comment by VHSgunzo** [comment]
This is very strange, since I have no problems with relogin in the same account, and the game itself periodically forces me to log back into the account for some time when I don't play it. 
You can try to apply another patch related to xlua, but I'm not sure that it will help, since everything should work fine without it.

run the script from the directory with GenshinImpact.exe
`
/home/$USER/.local/share/LutrisWine/winepfx/drive_c/Program Files/gi_patch260/patch_anti_logincrash.sh
`

**Comment by MaddPenguin** [comment]
Patch applied. Still not working, Thanks for helping

**Comment by VHSgunzo** [comment]
I noticed in the debug log that you have enabled Lutri runtime.  Try disabling it in the settings and restarting the game.

I am not the author of the patch itself, I only built it into my project by writing an automated DB script for the EXE. 
Try contacting the patch author: [Krock](https://notabug.org/Krock/dawn)

**Comment by cindrmon** [comment]
> Hi, I think there is something wrong with the network settings on your system. I check the login in this game every time, it is successful. In any case, if the patch had not been applied, the game would simply not have started. I have now listened to my traffic at the time of a successful login to the account and caught which servers the game is knocking on. Try to open Lutris Wine CMD (<lutris-wine -cmd> or from menu) and ping these servers:
> 
> ```
> sdk-os-static.hoyoverse.com  ->  443,tcp
> autopatchhk.yuanshen.com  ->  443,tcp
> log-upload-os.hoyoverse.com  ->  80,tcp
> osusadispatch.yuanshen.com  ->  443,tcp
> abtest-api-data-sg.hoyoverse.com  ->  443,tcp
> static.geetest.com  ->  443,tcp
> api-na.geetest.com  ->  443,tcp
> api-account-os.hoyoverse.com  ->  443,tcp
> hk4e-sdk-os-static.hoyoverse.com  ->  443,tcp
> hk4e-sdk-os.hoyoverse.com  ->  443,tcp
> osasiadispatch.yuanshen.com  ->  443,tcp
> oseurodispatch.yuanshen.com  ->  443,tcp
> dispatchosglobal.yuanshen.com  ->  443,tcp
> ```
> 
> And send me the ping results.
> 
> Do you have other online games or maybe a launcher like steam or epic game or others installed through Lutris Wine? Do they have access to the network? Maybe a firewall is blocking access to the network for Lutris Wine?


i noticed something off when i tried pinging `log-upload-os.hoyoverse.com`...

```
C:\>ping log-upload-os.hoyoverse.com
Pinging log-upload-os.hoyoverse.com [0.0.0.0] with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.

Ping statistics for 0.0.0.0
        Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)

C:\>
```

also, i feel like it has something to do with the modified `/etc/hosts` file, especially these lines:

```

# Genshin logging servers (do not remove!)
0.0.0.0 log-upload-os.hoyoverse.com
0.0.0.0 overseauspider.yuanshen.com

# Optional Unity proxy/cdn servers
0.0.0.0 prd-lender.cdp.internal.unity3d.com
0.0.0.0 thind-prd-knob.data.ie.unity3d.com
0.0.0.0 thind-gke-usc.prd.data.corp.unity3d.com
0.0.0.0 cdp.cloud.unity3d.com
0.0.0.0 remote-config-proxy-prd.uca.cloud.unity3d.com
```

is it alright to ask for help on this? using a vpn will not let `lutris-wine` work properly at all...

**Comment by VHSgunzo** [comment]
> i noticed something off when i tried pinging `log-upload-os.hoyoverse.com`...
> 
> ```
> C:\>ping log-upload-os.hoyoverse.com
> Pinging log-upload-os.hoyoverse.com [0.0.0.0] with 32 bytes of data:
> PING: transmit failed. General failure.
> PING: transmit failed. General failure.
> PING: transmit failed. General failure.
> PING: transmit failed. General failure.
> 
> Ping statistics for 0.0.0.0
>         Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)
> 
> C:\>
> ```
> 
> also, i feel like it has something to do with the modified `/etc/hosts` file, especially these lines:
> 
> ```
> 
> # Genshin logging servers (do not remove!)
> 0.0.0.0 log-upload-os.hoyoverse.com
> 0.0.0.0 overseauspider.yuanshen.com
> 
> # Optional Unity proxy/cdn servers
> 0.0.0.0 prd-lender.cdp.internal.unity3d.com
> 0.0.0.0 thind-prd-knob.data.ie.unity3d.com
> 0.0.0.0 thind-gke-usc.prd.data.corp.unity3d.com
> 0.0.0.0 cdp.cloud.unity3d.com
> 0.0.0.0 remote-config-proxy-prd.uca.cloud.unity3d.com
> ```
> 
> i did try using a VPN, but `lutris-wine` does not run at all when I activate a VPN. It is only when I disable VPN connection, it works properly.
> 
> is it alright to ask for help on this? using a vpn will not let `lutris-wine` work properly at all...

All hosts added to /etc/hosts when applying the patch should not be pinged, this is done to
try to hide users using the patch.  
By itself, lutris-wine cannot fail to start when the VPN is turned on, because it does not use the Internet at startup, except to check the status of the Internet connection. 
Describe in more detail what you are doing, which VPN you are using and, if possible, preferably record a video of what you are doing.

**Comment by cindrmon** [comment]
> All hosts added to /etc/hosts when applying the patch should not be pinged, this is done to try to hide users using the patch. By itself, lutris-wine cannot fail to start when the VPN is turned on, because it does not use the Internet at startup, except to check the status of the Internet connection. Describe in more detail what you are doing, which VPN you are using and, if possible, preferably record a video of what you are doing.

---

Okay, I think I feel like there is a bit of error on my part.

For one, I guess I wasn't patient enough to wait that it actually loads while using the VPN. It just so happens that the reason why it took so long to launch the game is that it was trying to connect to my local network drives (which can't be found while on a VPN), so I do apologise for that.

Another thing, even though I am already connected through a VPN, it still doesn't show the captcha when trying to login for the first time.

The VPN I use for the demo is ProtonVPN Free. It autoconnects to a free tier Netherlands server. I might still try out again using my own VPN server connected through OpenVPN to see how it fares. 

[Click Here](https://cloud.cindrmon.blue/s/qF5bH3mrKpZb4Cn) for the video.

The usual process of how I tried to troubleshoot this problem is as follows:

### Attempt 1 (Using Proton VPN the standard way)

1. Launch Proton VPN Client
2. Click 'Quick Connect' on the Proton VPN Client (in this case, it would usually be connected to a Netherlands server)
3. Launch a Terminal and `cd` to the 'Genshin impact game' folder
4. Run `lutris-wine ./GenshinImpact.exe`
5. Wait (I already lost patience and exited the command without realising that it just took too long to run the game)

### Attempt 2 (Using Proton VPN on-and-off way)

1. Launch Proton VPN Client
2. Launch a Terminal and `cd` to the 'Genshin impact game' folder
3. Write out the command `lutris-wine ./GenshinImpact.exe` in preparation.
4. Run the aforementioned command while quickly clicking the 'Quick Connect' button on the Proton VPN Client.
5. Game Launches, but login captcha doesn't show.

### Attempt 3 (Attempt 1 but with patience)
> This is the one I showed on the video right now as my current attempt

1. Launch Proton VPN Client
2. Click 'Quick Connect' on the Proton VPN Client (in this case, it would usually be connected to a Netherlands server)
3. Launch a Terminal and `cd` to the 'Genshin impact game' folder
4. Run `lutris-wine ./GenshinImpact.exe`
5. Wait (this time, it took 3-5 minutes before the game launches, and I noticed in the terminal that it attempted to connect to my network drives, which timed out and the game suddenly started)
6. Game Launches, but login captcha doesn't show. (I waited for another 5-6 minutes before I exited the game again)

**Comment by MaddPenguin** [comment]
I used to use ProtonVPN, but Cloudflare Warp works for me too. Maybe u can give that a try.

**Comment by cindrmon** [comment]
> I used to use ProtonVPN, but Cloudflare Warp works for me too. Maybe u can give that a try.

I'll try using Cloudflare Warp. Just to clarify, is it [this](https://aur.archlinux.org/packages/cloudflare-warp-bin) cloudflare warp?

**Comment by VHSgunzo** [comment]
> I'll try using Cloudflare Warp. Just to clarify, is it [this](https://aur.archlinux.org/packages/cloudflare-warp-bin) cloudflare warp?
> 
> EDIT: even if i used [this cloudflare warp](https://aur.archlinux.org/packages/cloudflare-warp-bin), it still doesn't work at all.

What disk is the game on? Can you send a debug log?

**Comment by cindrmon** [comment]
> Can you send a debug log?
> 
> The delay in launching lutris-wine when the VPN is turned on is due to calling "df", for some reason your VPN spoils the routes to network drives, perhaps after turning on the VPN you need to remount all network drives. But this is only part of the problem, but why you don't have a captcha is not yet clear. But again, if the patch didn't work, the game wouldn't have started at all. I still think that the game cannot reach its captcha service and there is a problem with the network

I ran `lutris-wine -debug GenshinImpact.exe` again 2 times: one using cloudflare warp and the other using ProtonVPN. I waited for 5 minutes each if ever the hoyoverse captcha ever does show up during the login process, but to no avail, no hoyoverse captcha.

listed below are the results of the debug logs for both attempts.

- [Debug Log Using Cloudflare Warp](https://bin.disroot.org/?dd13ff301ce1bc6b#99vVpTnQh4rzXqtz19J3WUzHVZ17gDStfBMR4NynMgCX)
- [Debug Log Using Proton VPN](https://bin.disroot.org/?bf61d80c2c4cba9c#2ocUdW1Bvxbk6xVeqGhM5ML4J3SSQeggMwGeiSeWQXQe)

**Comment by VHSgunzo** [comment]
> I ran `lutris-wine -debug GenshinImpact.exe` again 2 times: one using cloudflare warp and the other using ProtonVPN. I waited for 5 minutes each if ever the hoyoverse captcha ever does show up during the login process, but to no avail, no hoyoverse captcha.
> 
> listed below are the results of the debug logs for both attempts.
> 
> * [Debug Log Using Cloudflare Warp](https://bin.disroot.org/?dd13ff301ce1bc6b#99vVpTnQh4rzXqtz19J3WUzHVZ17gDStfBMR4NynMgCX)
> * [Debug Log Using Proton VPN](https://bin.disroot.org/?bf61d80c2c4cba9c#2ocUdW1Bvxbk6xVeqGhM5ML4J3SSQeggMwGeiSeWQXQe)

I see that the system wine is being used, try installing the latest version of Proton GE using the wine manager built into lutris-wine and run the game again, but without a VPN

**Comment by cindrmon** [comment]
omg it worked! thanks man! i didn't know it would just be an issue in terms of using the wrong wine version.. thanks again man!

**Comment by cindrmon** [comment]
@VHSgunzo i do have one last question though.. since the [video demo](https://www.youtube.com/watch?v=FhB2LPqUnSE) you've made, how long have you played genshin on linux? and had that account been banned while you were playing genshin on linux? and would you continue having updated patches for genshin on linux on future versions? just curious about it..

**Comment by VHSgunzo** [comment]
@cindrmon 
My account has not been blocked since its creation (v2.5) and I am updating the patch from version 2.5 of the game and will continue to do so if I have free time

**Comment by cindrmon** [comment]
> @cindrmon My account has not been blocked since its creation (v2.5) and I am updating the patch from version 2.5 of the game and will continue to do so if I have free time

i see, thanks! i'll be using an alternate account just in case that there would still be a chance the account gets banned or anything, and i would try to experiment it for the next 3 years to see how long that account can last on linux. if it would prove that the account lasts for that long, it may be a chance imma use my real account for it. if not, then i guess genshin on linux isn't ready yet. 

again, thank you for the effort!
