### ISSUE TITLE
Lots of desktop entries created

### ISSUE THREAD

**Issue by dkodar20** [VHSgunzo/lutris-wine#2]
The tool is of great help, but it created a lot of desktop entries which I was unable to find in both `/usr/share/applications` and in `~/.local/share/applications`. Is there a possible way to fix it? (I am using the latest version of Manjaro-Gnome if that helps)

**Comment by VHSgunzo** [comment]
Hi, yes there are some inconvenient features in using GNOME, you need to enable an extension that will add a normal application menu. 
You can do this from the console:
**`sudo pacman -S gnome-menus`
`gnome-extensions enable apps-menu@gnome-shell-extensions.gcampax.github.com`**

After that, the normal application menu will appear on the taskbar.
During installation, my project creates additional categories for its shortcuts.
 
For the main shortcuts, the category is called "Lutris Wine"
![image](https://user-images.githubusercontent.com/57139938/168419266-27e048fd-03a6-4213-87f7-aa9fd55bb45e.png)

For the shortcuts that you will create, the category is called "Wine App"
![image](https://user-images.githubusercontent.com/57139938/168419366-d8a40f76-3290-4bf9-809f-cf4497e6a993.png)

The shortcuts themselves are in the path:
Main shortcuts
`/usr/share/applications/LutrisWine/`

Created shortcuts
`~/.local/share/applications/LutrisWineApp/`

**Comment by dkodar20** [comment]
The problem is that I use pop-shell gnome extension for windows tiling and the app launcher they have. Unfortunately, all of the lutris-wine applications show up even if I just want to open lutris or wine, which makes it a bit of a hassle. This has happened before with some other project builds as well which involve creating a lot of desktop entries (the one which is at the top of my head currently is EasyEffects), but the easy fix for that was just removing them from `/usr/share/applications` but I cannot find the desktop files for lutris-wine applications there. I am not really sure whether there is a fix to this, but if there was one then it would be really convenient. 
![image](https://user-images.githubusercontent.com/63411969/168445318-70d6ac27-8768-4072-8c04-bb28f80d4a48.png)
The above image shows what I wanted to achieve.

One fix which I could think of is that I build the project with the `NoDsiplay` option as true in the [applications](https://github.com/VHSgunzo/lutris-wine/tree/main/usr/share/applications/LutrisWine) installed by lutris-wine but I am not sure whether it will work.  
Another possible qol fix might be that there is just a single gui page which has options to open all these applications rather than having them separately. But I guess there might have been some reason for why you did not implement it that way. Kindly let me know if there are any fixes. I could also try to help you out in case you don't have time to work on these anymore.

**Comment by VHSgunzo** [comment]
I installed this extension and when searching for programs like this, it does not show me shortcuts from lutris-wine, despite the fact that everything is displayed in the application menu as it should. 
I don't know why these shortcuts bother you so much, but you can delete them, I wrote their location above.
Their functionality is duplicated in the GUI settings on the "Tools" tab
![image](https://user-images.githubusercontent.com/57139938/168448362-becf0709-f795-4401-94f3-2b0f8d1df0ac.png)
And in the tray when launching the EXE and it is also available from the console.

Although, to begin with, you can try to hide them, since they are needed for quick access from the mouse context menu in the "run with" option.
I wrote a small one-line script for hide them:
**`for shortcut in $(ls /usr/share/applications/LutrisWine/) ; do sudo sed -i 's/NoDisplay=false/NoDisplay=true/' "/usr/share/applications/LutrisWine/$shortcut" ; done`**

As for the help, I would not refuse it, offer your developments and corrections for the project in the form of pull requests

**Comment by dkodar20** [comment]
I see. Thanks a lot. Closing the issue.
